---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _portraits
  label: Portraits
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
